In [1]:
import numpy as np
import time

### Creating Vectors

In [3]:
a = np.zeros(4)
print(f"np.zeros(4) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.zeros((4,))
print(f"np.zeros((4,)) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.random_sample(4)
print(f"np.random.random_sample(4) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros((4,)) : a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4) : a = [0.67830781 0.21899283 0.3443824  0.9914648 ], a shape = (4,), a data type = float64


In [4]:
a = np.arange(4.)
print(f"np.arange(4.) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.rand(4)
print(f"np.random.rand(4) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.) : a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4) : a = [0.77339119 0.31377008 0.02691542 0.19144534], a shape = (4,), a data type = float64


In [5]:
a = np.array([5, 4, 3, 2])
print(f"np.array([5, 4, 3, 2]) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.array([5., 4, 3, 2])
print(f"np.array([5., 4, 3, 2]) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5, 4, 3, 2]) : a = [5 4 3 2], a shape = (4,), a data type = int64
np.array([5., 4, 3, 2]) : a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


### Indexing

In [14]:
a = np.arange(10)
print(a)

print(f"a[2].shape: {a[2].shape}")
print(f"a[2] = {a[2]}")
print(f"a[-1] = {a[-1]}")

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: ()
a[2] = 2
a[-1] = 9


### Slicing

In [29]:
a = np.arange(10)
print(f"a          = {a}")

c = a[2:7:1]
print(f"a[2:7:1]   =", c)

c = a[2:7:2]
print(f"a[2:7:2]   =", c)

c = a[3:]
print(f"a[3:]      =", c)

c = a[:3]
print(f"a[:3]      =", c)

c = a[:]
print(f"a[:]       =", c)

a          = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1]   = [2 3 4 5 6]
a[2:7:2]   = [2 4 6]
a[3:]      = [3 4 5 6 7 8 9]
a[:3]      = [0 1 2]
a[:]       = [0 1 2 3 4 5 6 7 8 9]


In [37]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
 
b = -a
print(f"b = -a        : {b}")

b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2.     : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2.     : [ 1  4  9 16]


In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])

print(f"a = {a}")
print(f"b = {b}")

# binary operators work element wise
# note that the vectors must be the same size

print(f"a + b = {a + b}")

a = [1 2 3 4]
b = [-1 -2  3  4]
binary operators work element wise
a + b = [0 0 6 8]


### Multiplying with a Scalar Value

In [51]:
a = np.array([1, 2, 3, 4])
b = 5 * a
print(f"a =       : {a}")
print(f"b = 5 * a : {b}")

a =       : [1 2 3 4]
b = 5 * a : [ 5 10 15 20]


### Dot Product

In [52]:
# manual for loop
def my_dot(a, b):
    """
    Compute the dot product of two vectors
    
    Args:
        a (ndarray (n,)): input vector
        b (ndarray (n,)): input vector with same dimension as a
    
    Returns:
        x (scalar):
    """
    
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [53]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [55]:
c = np.dot(a, b)
print(f"Numpy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ")

c = np.dot(b, a)
print(f"Numpy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

Numpy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
Numpy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


### Matrices - two dimensional arrays

In [56]:
a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2, 1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1, 1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.32717045]]


In [57]:
a = np.array([[5], [4], [3]])
print(f"a shape = {a.shape}, a = {a}")

a = np.array([[5],
              [4],
              [3],]);
print(f"a shape = {a.shape}, a = {a}")

a shape = (3, 1), a = [[5]
 [4]
 [3]]
a shape = (3, 1), a = [[5]
 [4]
 [3]]


In [65]:
a = np.arange(6).reshape(-1,2)
print(f"a shape = {a.shape}, \na = {a}")

a shape = (3, 2), 
a = [[0 1]
 [2 3]
 [4 5]]


In [66]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

print("\na[0, 2:7:1] = ", a[0, 2:7:1], ", a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1;D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

a[0, 2:7:1] =  [2 3 4 5 6] , a[0, 2:7:1].shape = (5,) a 1;D array
